name: zefyr
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^15.2.3

  riverpod_annotation: ^2.6.1
  intl: ^0.20.2
  livekit_client: ^2.4.8
  flutter_riverpod: ^2.6.1

  flutter_svg: ^2.2.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  connectivity_plus: ^6.1.4
  dio: ^5.8.0+1
  drift_flutter: ^0.2.4
  drift: ^2.27.0
  drift_dev: ^2.27.0
  path_provider: ^2.1.5
  path: ^1.9.1
  google_sign_in: ^7.0.0
  flutter_dotenv: ^5.2.1
  email_validator: ^3.0.0
  collection: ^1.19.1
  skeletonizer: ^2.1.0
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.5.3
  convex_bottom_bar: ^3.2.0

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/webp/
    - assets/icons/
    - .env
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
